### ISSUE TITLE
gcc compile error

### ISSUE THREAD

**Issue by icyfox168168** [Angold-4/weicc#1]
tokenize.c:(.text+0xd0f): undefined reference to `open_memstream'

Temp\ccmOOetG.o:parse.c:(.text+0x1b48): undefined reference to `strndup'

**Comment by Angold-4** [comment]
Hey, please tell me which platform did you use, and how do you compile that file?
I've tested on both Ubuntu 20.04 and MacOS Monterey with Makefile (gcc), works fine I think :)

**Comment by icyfox168168** [comment]
win 10
